output HEADLESS-1 mode 1280x720
output * bg #261631 solid_color
font pango:JetBrainsMono Nerd Font 11
default_border pixel 2
client.focused #dca7ff #3a185d #fff7ff #dca7ff #dca7ff
gaps inner 8
gaps outer 8
focus_follows_mouse no
