xwayland disable
output HEADLESS-1 mode 1000x700
output * bg #13091f solid_color
seat seat0 fallback true
focus_follows_mouse no
workspace 99: Control
bindsym Mod4+1 workspace number "1: Ghost"
bindsym Mod4+2 workspace number "2: Orbit"
bindsym Mod4+3 workspace number "3: Lab"
bindsym Mod4+4 workspace number "4: Signal"
bindsym Mod4+5 workspace number "5: Lounge"
bindsym Mod4+6 workspace number 6
bindsym Mod4+7 workspace number 7
bindsym Mod4+8 workspace number 8
bindsym Mod4+9 workspace number 9
bindsym Mod4+Shift+1 move container to workspace number "1: Ghost"
bindsym Mod4+Shift+2 move container to workspace number "2: Orbit"
bindsym Mod4+Shift+3 move container to workspace number "3: Lab"
bindsym Mod4+Shift+4 move container to workspace number "4: Signal"
bindsym Mod4+Shift+5 move container to workspace number "5: Lounge"
bindsym Mod4+Shift+6 move container to workspace number 6
bindsym Mod4+Shift+7 move container to workspace number 7
bindsym Mod4+Shift+8 move container to workspace number 8
bindsym Mod4+Shift+9 move container to workspace number 9
bindsym Mod4+Shift+0 move container to workspace number "10: Strata"
assign [app_id="^oldbook-strata$"] workspace number "10: Strata"
no_focus [app_id="^oldbook-strata$"]
