xwayland disable
output HEADLESS-1 mode 1000x700
output * bg #13091f solid_color
seat seat0 fallback true
focus_follows_mouse no
workspace 2
assign [app_id="^oldbook-strata$"] workspace number 0
no_focus [app_id="^oldbook-strata$"]
