"""Apply explicitly owned lease state; migration and radio policy live elsewhere.

The caller must be the exclusive controller for protocol 196 on this interface.
On any failure it must block the radio BEFORE removing ``NetworkError.owned``.
Records are process-local capabilities: stale revisions cannot remove a renewed
lease. Persisted diagnostics contain addresses and belong in root-private state.
"""
from dataclasses import asdict, dataclass, replace
from ipaddress import IPv6Address, IPv6Interface, ip_address, ip_interface, ip_network
import json
import os
from pathlib import Path
import re
import select
import selectors
import signal
import stat
import subprocess
import sys
import time

from .lease import Lease, _interface


PROTOCOL = 196
METRIC = 42700
# Include IPv6 DAD while leaving time to ACK within the hook deadline.
APPLY_TIMEOUT = 10.0
REMOVE_TIMEOUT = 12.0
SIGNATURE = '# Generated by resolvconf'
_CACHE_SUBSCRIBERS = {'dnsmasq': 'dnsmasq', 'named': 'named', 'pdns_recursor': 'pdns_recursor',
                      'pdnsd': 'pdnsd', 'resolvectl': 'resolvectl',
                      'systemd-resolved': 'systemd_resolved', 'unbound': 'unbound'}

# Fixed Python code; all network parameters travel as argv or stdin, never code.
# The inner process waits for the owner's pidfd handshake before it may mutate.
_COMMAND_INNER = '''import os,sys
ready,gate,hostproc=map(int,sys.argv[1:4])
os.write(ready,b"R");os.close(ready)
frame=os.read(gate,64)
if not frame.startswith(b"G") or not frame.endswith(b"\\n") or not frame[1:-1].isdigit(): sys.exit(112)
os.close(gate)
os.environ["OPENRESOLV_HOST_PID"]=frame[1:-1].decode("ascii")
os.environ["OPENRESOLV_HOST_PROC_FD"]=str(hostproc)
os.execv(sys.argv[4],sys.argv[4:])
'''
_COMMAND_OUTER = '''import ctypes,os,signal,sys
libc=ctypes.CDLL(None,use_errno=True)
if libc.prctl(1,signal.SIGKILL,0,0,0)!=0 or os.getppid()!=int(sys.argv[1]): sys.exit(111)
os.execv(sys.argv[2],sys.argv[2:])
'''


@dataclass(frozen=True)
class Address:
    family: int
    cidr: str
    protocol: int = PROTOCOL


@dataclass(frozen=True)
class Route:
    family: int
    destination: str
    gateway: str | None
    protocol: int = PROTOCOL
    metric: int = METRIC
    source: str | None = None


@dataclass(frozen=True)
class Snapshot:
    ifindex: int
    addresses: frozenset[Address]
    routes: frozenset[Route]
    tentative: frozenset[Address] = frozenset()
    failed: frozenset[Address] = frozenset()
    secondary: frozenset[Address] = frozenset()


@dataclass(frozen=True)
class IPv6Profile:
    """Explicit static configuration from a trusted private profile, never DHCP.

    An empty profile removes only previously owned IPv6 configuration. It does
    not flush legacy state, disable RA/SLAAC, or alter any interface sysctl.
    """
    addresses: tuple[IPv6Interface, ...] = ()
    routers: tuple[IPv6Address, ...] = ()

    def __post_init__(self):
        if (type(self.addresses) is not tuple or len(self.addresses) > 4
                or type(self.routers) is not tuple or len(self.routers) > 4):
            raise ValueError('IPv6 profile lists must be bounded tuples')
        for address in self.addresses:
            if (type(address) is not IPv6Interface or address.ip.is_unspecified
                    or address.ip.is_multicast or address.ip.is_loopback or address.ip.is_link_local
                    or address.ip.ipv4_mapped is not None or address.scope_id is not None):
                raise ValueError('invalid static IPv6 profile address')
        for router in self.routers:
            if (type(router) is not IPv6Address or router.is_unspecified or router.is_multicast
                    or router.is_loopback or router.ipv4_mapped is not None or router.scope_id is not None
                    or not self.addresses or (not router.is_link_local
                        and not any(router in address.network for address in self.addresses))):
                raise ValueError('invalid IPv6 profile gateway')
        if len(set(self.addresses)) != len(self.addresses) or len(set(self.routers)) != len(self.routers):
            raise ValueError('duplicate IPv6 profile parameter')


@dataclass(frozen=True)
class OwnedState:
    generation: str
    interface: str
    ifindex: int
    revision: int
    addresses: tuple[Address, ...] = ()
    routes: tuple[Route, ...] = ()
    provider: str | None = None
    dns_contents: tuple[str, ...] = ()

    def to_dict(self):
        return asdict(self)


class NetworkError(RuntimeError):
    def __init__(self, message, owned=None):
        super().__init__(message)
        self.owned = owned


def _servers(content):
    result = []
    for line in content.splitlines():
        tokens = line.split()
        if tokens and tokens[0] == 'nameserver':
            if len(tokens) != 2:
                raise RuntimeError('invalid resolver nameserver line')
            result.append(str(ip_address(tokens[1])))
    return tuple(result)


class LeaseApplier:
    def __init__(self, generation, interface='wlan0', *, backend=None, check=lambda: None, journal=None):
        if not isinstance(generation, str) or not re.fullmatch(r'[0-9a-f]{32}', generation):
            raise ValueError('invalid lease generation')
        _interface(interface)
        self.generation, self.interface = generation, interface
        self.backend = NativeNetwork(journal=journal) if backend is None else backend
        self.journal = getattr(self.backend, 'journal', None) if journal is None else journal
        if isinstance(self.backend, NativeNetwork) and journal is not None:
            if self.backend.journal is not None and self.backend.journal is not journal:
                raise ValueError('native backend and applier journals differ')
            self.backend.journal = journal
        self.check = check
        self._current = None
        self._revision = 0
        self._deadline = 0
        self._cancellable = True

    @property
    def current(self):
        """Latest partial ownership, including after KeyboardInterrupt/SystemExit."""
        return self._current

    def _checkpoint(self):
        if self._cancellable:
            self.check()
        if time.monotonic() >= self._deadline:
            raise RuntimeError('network operation deadline exceeded')

    def _op(self, name, *args):
        self._checkpoint()
        result = getattr(self.backend, name)(*args, deadline=self._deadline, check=self._checkpoint)
        self._checkpoint()
        return result

    def _record(self, candidate=None, **changes):
        if changes:
            candidate = replace(self._current, **changes)
        # A failed durable intent must neither change this capability nor open
        # the next native mutation gate. Failed narrowing keeps the wider set.
        if self.journal is not None:
            self.journal.record_owned(candidate)
        self._current = candidate

    def _require_current(self, owned):
        if owned is not self._current:
            raise RuntimeError('stale or foreign lease ownership record')

    def _snapshot(self):
        return self._op('snapshot', self.interface)

    def _verify_owned(self, snapshot, owned):
        if snapshot.ifindex != owned.ifindex:
            raise RuntimeError('network interface identity changed')
        for address in owned.addresses:
            if any(value.family == address.family and value.cidr == address.cidr
                   and value != address for value in snapshot.addresses):
                raise RuntimeError('owned address was replaced')
        for route in owned.routes:
            if any((value.family, value.destination, value.metric) ==
                   (route.family, route.destination, route.metric) and value != route
                   for value in snapshot.routes):
                raise RuntimeError('owned route was replaced')
        if owned.provider:
            content = self._op('provider', owned.provider)
            if content is not None and content not in owned.dns_contents:
                raise RuntimeError('owned resolver provider was replaced')

    def _desired(self, lease, profile):
        addresses = (Address(4, str(lease.address)),) + tuple(
            Address(6, str(address)) for address in profile.addresses)
        routes = []
        for interface in (lease.address, *profile.addresses):
            route = Route(interface.version, str(interface.network), None,
                          source=str(interface.ip))
            if not any((item.family, item.destination) == (route.family, route.destination)
                       for item in routes):
                routes.append(route)
        # /32 and off-prefix gateways require an explicit owned on-link host route.
        for router in lease.routers:
            if router not in lease.address.network:
                routes.append(Route(4, str(router) + '/32', None, source=str(lease.address.ip)))
        for family, gateways, source in ((4, lease.routers, str(lease.address.ip)),
                                         (6, profile.routers, None)):
            for index, router in enumerate(gateways):
                routes.append(Route(family, 'default', str(router), metric=METRIC + 1 + index,
                                    source=source))
        return addresses, tuple(dict.fromkeys(routes))

    def _remove_resources(self, addresses, routes):
        # Routes first, then addresses; never issue a flush or an untagged route delete.
        for route in reversed(routes):
            snapshot = self._snapshot()
            self._verify_owned(snapshot, self._current)
            if route in snapshot.routes:
                self._op('delete_route', self.interface, route)
            if route in self._snapshot().routes:
                raise RuntimeError('owned route deletion was not applied')
            self._record(routes=tuple(value for value in self._current.routes if value != route))
        for address in reversed(addresses):
            snapshot = self._snapshot()
            self._verify_owned(snapshot, self._current)
            if address in snapshot.addresses:
                if address.family == 4 and address not in snapshot.secondary:
                    network = ip_interface(address.cidr).network
                    if any(value.family == 4 and value != address
                           and ip_interface(value.cidr).network == network
                           for value in snapshot.addresses):
                        # Linux may remove secondary addresses with their primary.
                        # Do not alter promote_secondaries or silently delete peers.
                        raise RuntimeError('primary IPv4 address has another address in its prefix')
                self._op('delete_address', self.interface, address)
            if address in self._snapshot().addresses:
                raise RuntimeError('owned address deletion was not applied')
            self._record(addresses=tuple(value for value in self._current.addresses if value != address))

    def _remove_dns(self, *, recovered=False):
        owned = self._current
        if not owned.provider:
            return
        # Recovery may repair a torn managed payload using current providers;
        # both paths still refuse an unmanaged replacement before openresolv.
        self._op('regenerate_dns' if recovered else 'resolver')
        content = self._op('provider', owned.provider)
        if content is not None:
            if content not in owned.dns_contents:
                raise RuntimeError('owned resolver provider was replaced')
            self._op('delete_provider', owned.provider)
        if self._op('provider', owned.provider) is not None:
            raise RuntimeError('resolver provider deletion was not applied')
        if recovered:
            self._op('regenerate_dns')
        output = set(self._op('resolver'))
        remaining = self._op('all_provider_dns')
        removed = {server for content in owned.dns_contents for server in _servers(content)}
        if (removed & output) - remaining:
            raise RuntimeError('resolver subscriber retained unowned lease nameservers')
        self._record(provider=None, dns_contents=())

    def apply(self, lease, previous=None, *, ipv6=IPv6Profile()):
        self._deadline, self._cancellable = time.monotonic() + APPLY_TIMEOUT, True
        try:
            self._require_current(previous)
            if type(lease) is not Lease or lease.interface != self.interface or type(ipv6) is not IPv6Profile:
                raise RuntimeError('lease or profile does not match the applier')
            self._op('resolver')
            snapshot = self._snapshot()
            if previous is not None:
                self._verify_owned(snapshot, previous)
            addresses, routes = self._desired(lease, ipv6)
            old_addresses = () if previous is None else previous.addresses
            old_routes = () if previous is None else previous.routes
            for address in addresses:
                if any(value.family == address.family and value.cidr == address.cidr
                       and value not in old_addresses for value in snapshot.addresses):
                    raise RuntimeError('refusing an existing unowned lease address')
            for route in routes:
                if any((value.family, value.destination, value.metric) ==
                       (route.family, route.destination, route.metric) and value not in old_routes
                       for value in snapshot.routes):
                    raise RuntimeError('refusing an existing unowned lease route')
            provider = f'privacyctl.{self.generation}.{self.interface}'
            if previous is None and self._op('provider', provider) is not None:
                raise RuntimeError('refusing an existing resolver generation')
            self._revision += 1
            self._record(OwnedState(self.generation, self.interface, snapshot.ifindex, self._revision)
                         if previous is None else replace(previous, revision=self._revision))
            self._remove_resources(tuple(value for value in old_addresses if value not in addresses),
                                   tuple(value for value in old_routes if value not in routes))
            for address in addresses:
                snapshot = self._snapshot()
                self._verify_owned(snapshot, self._current)
                if address not in snapshot.addresses:
                    self._record(addresses=tuple(dict.fromkeys((*self._current.addresses, address))))
                    self._op('add_address', self.interface, address, lease.lease_seconds)
                elif address.family == 4:
                    self._op('renew_address', self.interface, address, lease.lease_seconds)
            # Let IPv6 DAD complete within this same operation deadline.
            while True:
                snapshot = self._snapshot()
                if snapshot.failed.intersection(addresses):
                    raise RuntimeError('IPv6 duplicate-address detection failed')
                if not snapshot.tentative.intersection(addresses):
                    break
                self._checkpoint()
                time.sleep(min(0.025, max(0, self._deadline - time.monotonic())))
            for route in routes:
                snapshot = self._snapshot()
                self._verify_owned(snapshot, self._current)
                if route not in snapshot.routes:
                    self._record(routes=tuple(dict.fromkeys((*self._current.routes, route))))
                    self._op('add_route', self.interface, route)
            if lease.dns:
                self._op('resolver')
                content = ''.join(f'nameserver {server}\n' for server in lease.dns)
                existing = self._op('provider', provider)
                if existing is not None and existing not in self._current.dns_contents:
                    raise RuntimeError('resolver provider changed before renewal')
                possibilities = tuple(dict.fromkeys((*self._current.dns_contents, content)))
                self._record(provider=provider, dns_contents=possibilities)
                self._op('set_provider', provider, content)
                if self._op('provider', provider) != content:
                    raise RuntimeError('resolver provider update was not applied')
                if not set(map(str, lease.dns)).issubset(self._op('resolver')):
                    raise RuntimeError('resolver subscriber did not publish lease nameservers')
                self._record(dns_contents=(content,))
            else:
                self._remove_dns()
            snapshot = self._snapshot()
            self._verify_owned(snapshot, self._current)
            if not set(addresses).issubset(snapshot.addresses) or not set(routes).issubset(snapshot.routes):
                raise RuntimeError('network state verification failed')
            return self._current
        except Exception as error:
            raise NetworkError(str(error), self._current) from error

    def remove(self, owned):
        """Remove verified state after the owner blocks; cancellation cannot veto cleanup."""
        self._deadline, self._cancellable = time.monotonic() + REMOVE_TIMEOUT, False
        try:
            self._require_current(owned)
            # Process ownership can precede the first network ownership record:
            # even the initial resolver probe may retain a failed command.
            self._op('drain_pending')
            if owned is None:
                return None
            self._verify_owned(self._snapshot(), owned)
            self._remove_dns()
            self._remove_resources(self._current.addresses, self._current.routes)
            self._record(None)
            return None
        except Exception as error:
            raise NetworkError(str(error), self._current) from error

    def remove_recovered(self, permit, *, deadline, check=lambda: None):
        """Consume only coordinator-issued recovery authority, never disk JSON.

        The coordinator validates boot, proc view, cookie and all old writer
        deaths before granting a permit. Live records retain their separate
        object-identity fence; recovery cannot replace one in this applier.
        """
        from .recovery import validate_permit
        self._deadline = min(deadline, time.monotonic() + REMOVE_TIMEOUT)
        self._cancellable, self.check = True, check
        try:
            self._require_current(None)
            record = validate_permit(permit, generation=self.generation, interface=self.interface,
                                     deadline=self._deadline, check=self._checkpoint)
            resources = record['resources']
            owned = OwnedState(self.generation, self.interface, record['ifindex'], record['sequence'],
                               tuple(Address(**value) for value in resources['addresses']),
                               tuple(Route(**value) for value in resources['routes']),
                               resources['provider'], tuple(resources['dns_contents']))
            self._record(owned)
            self._op('drain_pending')
            self._verify_owned(self._snapshot(), owned)
            self._remove_dns(recovered=True)
            self._remove_resources(self._current.addresses, self._current.routes)
            snapshot = self._snapshot()
            if (any(value.protocol == PROTOCOL for value in snapshot.addresses)
                    or any(value.protocol == PROTOCOL for value in snapshot.routes)):
                raise RuntimeError('unexplained reserved-protocol state remains after recovery')
            self._record(None)
            return None
        except Exception as error:
            raise NetworkError(str(error), self._current) from error


class NativeNetwork:
    """Fixed-path iproute2/openresolv backend; explicit paths are trusted tests only.

    Tests using real commands need private network AND mount/PID namespaces.
    The normal resolver layout and ownership marker must already be established
    by a separately reviewed migration. Regeneration uses ``-u`` only after
    validating the intact managed signature, current providers and libc policy.
    """
    def __init__(self, *, ip='/sbin/ip', resolvconf='/usr/sbin/resolvconf',
                 resolver='/etc/resolv.conf', providers='/run/resolvconf/keys',
                 resolver_config='/etc/resolvconf.conf', subscribers='/usr/lib/resolvconf', journal=None):
        self.ip, self.resolvconf = str(ip), str(resolvconf)
        self.resolver_path, self.providers = Path(resolver), Path(providers)
        self.resolver_config, self.subscribers = Path(resolver_config), Path(subscribers)
        self._pending_cleanup = None
        self.journal = journal
        self._writer_pending = False

    def _finish_writer(self):
        if self._writer_pending:
            self.journal.writer_finished('native')
            self._writer_pending = False

    @staticmethod
    def _stop_command(process, descriptors):
        # pidfds cannot target a reused PID. Killing init closes the whole PID
        # namespace, including descendants that detached into another session.
        if descriptors[1] is None:
            # This direct Popen child has not been reaped, so its PID is still
            # ours even if acquiring the first pidfd failed (for example EMFILE).
            process.kill()
        for descriptor in descriptors:
            if descriptor is not None:
                try:
                    signal.pidfd_send_signal(descriptor, signal.SIGKILL)
                except ProcessLookupError:
                    pass
        deadline = time.monotonic() + 0.4
        pending = [descriptor for descriptor in descriptors if descriptor is not None]
        while pending:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise RuntimeError('network command namespace teardown did not complete')
            ready, _, _ = select.select(pending, [], [], remaining)
            pending = [descriptor for descriptor in pending if descriptor not in ready]
        process.wait(timeout=max(0.001, deadline - time.monotonic()))

    @staticmethod
    def _capture(process, outer_fd, deadline, check, content):
        if content is not None:
            data = content.encode('ascii')
            if len(data) > 2048:
                raise RuntimeError('network command input is too large')
            # The bounded payload fits PIPE_BUF in this initially empty pipe.
            os.write(process.stdin.fileno(), data)
            process.stdin.close()
        output, size = [], 0
        with selectors.DefaultSelector() as selector:
            for stream in (process.stdout, process.stderr):
                os.set_blocking(stream.fileno(), False)
                selector.register(stream, selectors.EVENT_READ, stream is process.stdout)
            selector.register(outer_fd, selectors.EVENT_READ, None)
            while selector.get_map():
                check()
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    raise RuntimeError('network command timed out')
                for key, _events in selector.select(min(remaining, 0.025)):
                    if key.data is None:
                        process.wait(timeout=max(0.001, deadline - time.monotonic()))
                        selector.unregister(key.fileobj)
                        continue
                    chunk = os.read(key.fd, 65536)
                    if not chunk:
                        selector.unregister(key.fileobj)
                        continue
                    size += len(chunk)
                    if size > 262144:
                        raise RuntimeError('network command output is too large')
                    if key.data:
                        output.append(chunk)
        return b''.join(output)

    def drain_pending(self, *, deadline, check):
        """Release retained command handles only after verified namespace death."""
        check()
        if self._pending_cleanup is not None:
            if time.monotonic() >= deadline:
                raise RuntimeError('network command cleanup deadline exceeded')
            pending_process, descriptors = self._pending_cleanup
            self._stop_command(pending_process, descriptors)
            self._finish_writer()
            for descriptor in descriptors:
                if descriptor is not None:
                    os.close(descriptor)
            self._pending_cleanup = None

    def _run(self, argv, *, deadline, check, content=None, operation='native-command'):
        argv = tuple(argv)
        check()
        if os.geteuid() != 0:
            raise RuntimeError('network application requires root')
        self.drain_pending(deadline=deadline, check=check)
        if self.journal is not None:
            self.journal.check_command(self, argv, content=content, deadline=deadline, check=check)
        ready_read = ready_write = gate_read = gate_write = host_proc = None
        process = None
        outer_fd = inner_fd = None
        try:
            ready_read, ready_write = os.pipe2(os.O_CLOEXEC)
            gate_read, gate_write = os.pipe2(os.O_CLOEXEC)
            # Keep the caller's PID view for the native resolver's shared lock.
            # The descriptor is read-only; parameters are never supplied by DHCP.
            host_proc = os.open('/proc', os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)
            command = [sys.executable, '-I', '-S', '-c', _COMMAND_OUTER, str(os.getpid()),
                       '/usr/bin/unshare', '--mount', '--propagation', 'private', '--pid', '--fork',
                       '--kill-child=SIGKILL', '--mount-proc', sys.executable, '-I', '-S', '-c',
                       _COMMAND_INNER, str(ready_write), str(gate_read), str(host_proc), *argv]
            process = subprocess.Popen(command,
                stdin=subprocess.PIPE if content is not None else subprocess.DEVNULL,
                stdout=subprocess.PIPE, stderr=subprocess.PIPE, start_new_session=True,
                pass_fds=(ready_write, gate_read, host_proc), cwd='/',
                env={'PATH': '/usr/sbin:/usr/bin:/sbin:/bin', 'LANG': 'C'})
            outer_fd = os.pidfd_open(process.pid)
            os.close(ready_write)
            ready_write = None
            os.close(gate_read)
            gate_read = None
            command_deadline = min(deadline, time.monotonic() + 0.75)
            while True:
                check()
                remaining = command_deadline - time.monotonic()
                if remaining <= 0:
                    raise RuntimeError('network command readiness timed out')
                if select.select([ready_read], [], [], min(remaining, 0.025))[0]:
                    break
            if os.read(ready_read, 2) != b'R':
                raise RuntimeError('network command namespace was not initialized')
            children = Path(f'/proc/{process.pid}/task/{process.pid}/children').read_text().split()
            if len(children) != 1:
                raise RuntimeError('network command namespace init is ambiguous')
            inner_pid = int(children[0])
            inner_fd = os.pidfd_open(inner_pid)
            namespace = os.readlink(f'/proc/{inner_pid}/ns/pid')
            if (namespace != os.readlink(f'/proc/{process.pid}/ns/pid_for_children')
                    or namespace == os.readlink('/proc/self/ns/pid')
                    or select.select([outer_fd, inner_fd], [], [], 0)[0]):
                raise RuntimeError('network command namespace identity changed')
            if self.journal is not None:
                # Persistence may have reached disk before raising; retain the
                # attempted slot until exact init death and durable completion.
                self._writer_pending = True
                self.journal.writer_started('native', inner_pid, inner_fd, operation)
                self.journal.check_command(self, argv, content=content, deadline=command_deadline, check=check)
            check()
            if time.monotonic() >= command_deadline:
                raise RuntimeError('network command gate deadline exceeded')
            os.write(gate_write, b'G' + str(inner_pid).encode('ascii') + b'\n')
            output = self._capture(process, outer_fd, command_deadline, check, content)
            if process.returncode:
                raise RuntimeError('network command failed')
            if inner_fd not in select.select([inner_fd], [], [], 0)[0]:
                raise RuntimeError('network command init survived completion')
            self._finish_writer()
            if self.journal is not None:
                self.journal.check_command(self, argv, content=content, deadline=command_deadline, check=check)
            if len(output) > 262144:
                raise RuntimeError('network command output is too large')
            check()
            return output.decode('ascii')
        except BaseException:
            if process is not None:
                try:
                    self._stop_command(process, (inner_fd, outer_fd))
                    self._finish_writer()
                except BaseException:
                    # No later command may start until these same handles prove
                    # teardown completed. A blocked owner can retry cleanup.
                    self._pending_cleanup = process, (inner_fd, outer_fd)
                    inner_fd = outer_fd = None
                    raise RuntimeError('network command cleanup remains pending') from None
            raise
        finally:
            for descriptor in (ready_read, ready_write, gate_read, gate_write, host_proc, outer_fd, inner_fd):
                if descriptor is not None:
                    os.close(descriptor)
            if process is not None:
                for stream in (process.stdin, process.stdout, process.stderr):
                    if stream is not None:
                        stream.close()

    @staticmethod
    def _read(path, *, missing=False):
        try:
            descriptor = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK | os.O_CLOEXEC)
        except FileNotFoundError:
            if missing:
                return None
            raise RuntimeError('native resolver state is not initialized') from None
        with os.fdopen(descriptor, 'rb') as stream:
            info = os.fstat(stream.fileno())
            if not stat.S_ISREG(info.st_mode) or info.st_uid != 0 or info.st_mode & 0o022 or info.st_size > 65536:
                raise RuntimeError('unsafe native resolver state file')
            data = stream.read(65537)
        if len(data) > 65536:
            raise RuntimeError('native resolver state is too large')
        return data.decode('ascii')

    def _provider_directory(self):
        # Reject legacy layouts and symlinked/writable state ancestors.
        for path in (self.providers, *self.providers.parents):
            info = path.lstat()
            sticky_root = info.st_uid == 0 and bool(info.st_mode & stat.S_ISVTX)
            if (not stat.S_ISDIR(info.st_mode) or info.st_uid != 0
                    or (info.st_mode & 0o022 and not sticky_root)):
                raise RuntimeError('unsafe native resolver provider directory')

    def provider(self, key, **options):
        self._provider_directory()
        if not re.fullmatch(r'privacyctl\.[0-9a-f]{32}\.[A-Za-z0-9][A-Za-z0-9_.-]{0,14}', key):
            raise RuntimeError('invalid resolver provider key')
        return self._read(self.providers / key, missing=True)

    def all_provider_dns(self, **options):
        self._provider_directory()
        paths = list(self.providers.iterdir())
        if len(paths) > 128:
            raise RuntimeError('too many native resolver providers')
        return {server for path in paths for server in _servers(self._read(path))}

    def _resolver_policy(self, **options):
        # Unpatched openresolv uses namespace-local $$ / kill -0 in its shared
        # lock. Require the explicit bridge ABI before any lease can be applied.
        if self._run([self.resolvconf, '--host-pid-lock-version'], **options).strip() != '1':
            raise RuntimeError('native resolver host-PID locking capability is required')
        self._resolver_configuration()

    def _resolver_configuration(self):
        # PID-isolated commands deliberately cannot restart host cache daemons.
        # Require an explicit libc-only policy; never modify policy to make a
        # command succeed. Migration must also account for installed libc.d hooks.
        policy = {}
        for line in self._read(self.resolver_config).splitlines():
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            key, separator, value = line.partition('=')
            if not separator or key in policy:
                raise RuntimeError('unsupported native resolver configuration')
            policy[key] = value
        expected = {'resolv_conf': str(self.resolver_path), 'state_dir': str(self.providers.parent),
                    'libc_restart': ':', **{name: 'NO' for name in _CACHE_SUBSCRIBERS.values()}}
        if policy != expected:
            raise RuntimeError('explicit libc-only resolver policy is required')
        for path in self.subscribers.iterdir():
            if path.name == 'libc.d':
                if any(path.iterdir()):
                    raise RuntimeError('resolver notification hooks need separate migration review')
            elif path.name not in {'libc', *_CACHE_SUBSCRIBERS}:
                raise RuntimeError('unknown native resolver subscriber')

    def _prepare_retirement_state(self):
        """Recreate only missing transient state/keys after validated policy.

        Never initialize openresolv with -I: it deletes unrelated providers.
        Existing legacy layouts, symlinks and writable ancestors are conflicts.
        """
        self._resolver_configuration()
        self._managed_resolver()
        if self.providers.name != 'keys':
            raise RuntimeError('DNS retirement requires the explicit keys layout')
        if os.path.lexists(self.providers.parent / 'interfaces'):
            raise RuntimeError('legacy resolver layout requires migration')
        for path in reversed((self.providers, *self.providers.parents)):
            try:
                info = path.lstat()
            except FileNotFoundError:
                if path not in (self.providers.parent, self.providers):
                    raise RuntimeError('resolver state ancestor is unavailable') from None
                path.mkdir(mode=0o755)
                info = path.lstat()
            sticky_root = info.st_uid == 0 and bool(info.st_mode & stat.S_ISVTX)
            if (not stat.S_ISDIR(info.st_mode) or info.st_uid != 0
                    or (info.st_mode & 0o022 and not sticky_root)):
                raise RuntimeError('unsafe native resolver provider directory')
        self._provider_directory()

    def retire_dns(self, permit, *, deadline, check=lambda: None):
        """Retire an exact old-boot DNS candidate using current provider inputs."""
        from .recovery import validate_dns_permit

        def checkpoint():
            return validate_dns_permit(permit, self, deadline=deadline, check=check)

        value = checkpoint()
        resources = value['resources']
        provider, contents = resources['provider'], resources['dns_contents']
        if provider is None:
            return
        self._prepare_retirement_state()
        checkpoint()
        content = self.provider(provider)
        if content is not None and content not in contents:
            raise RuntimeError('owned resolver provider was replaced')
        options = {'deadline': deadline, 'check': check}
        self.regenerate_dns(**options)
        checkpoint()
        content = self.provider(provider)
        if content is not None:
            if content not in contents:
                raise RuntimeError('owned resolver provider was replaced')
            self.delete_provider(provider, **options)
        checkpoint()
        if self.provider(provider) is not None:
            raise RuntimeError('resolver provider deletion was not applied')
        self.regenerate_dns(**options)
        checkpoint()
        output = set(self.resolver(**options))
        remaining = self.all_provider_dns()
        removed = {server for content in contents for server in _servers(content)}
        if (removed & output) - remaining:
            raise RuntimeError('resolver subscriber retained unowned lease nameservers')
        checkpoint()

    def _managed_resolver(self):
        content = self._read(self.resolver_path)
        if not content.startswith(SIGNATURE + '\n'):
            raise RuntimeError('resolver migration is required before lease application')
        return content

    def resolver(self, **options):
        self._resolver_policy(**options)
        return _servers(self._managed_resolver())

    def regenerate_dns(self, **options):
        # An intact managed signature is the existing destination authority. A
        # torn payload may be rebuilt, but a missing signature never grants
        # permission to take over an unmanaged file. Reuse openresolv's real
        # lock and fixed libc-only subscriber policy, never an old snapshot.
        self._resolver_policy(**options)
        self._managed_resolver()
        remaining = self.all_provider_dns(**options)
        self._run([self.resolvconf, '-u'], operation='native-dns-regenerate', **options)
        if not remaining.issubset(self.resolver(**options)):
            raise RuntimeError('resolver regeneration lost current provider nameservers')

    def set_provider(self, key, content, **options):
        self.provider(key)
        self._run([self.resolvconf, '-a', key], content=content, **options)

    def delete_provider(self, key, **options):
        self.provider(key)
        self._run([self.resolvconf, '-f', '-d', key], **options)

    def snapshot(self, interface, **options):
        _interface(interface)
        addresses, routes, tentative, failed, secondary = set(), set(), set(), set(), set()
        rows = json.loads(self._run([self.ip, '-j', '-N', 'address', 'show', 'dev', interface], **options))
        if len(rows) != 1 or rows[0].get('ifname') != interface:
            raise RuntimeError('network interface is missing or ambiguous')
        for data in rows[0].get('addr_info', []):
            family = 4 if data['family'] == 'inet' else 6
            protocol = data.get('protocol', 0)
            address = Address(family, str(ip_interface(f"{data['local']}/{data['prefixlen']}")),
                              int(protocol, 0) if isinstance(protocol, str) else int(protocol))
            addresses.add(address)
            if data.get('tentative'):
                tentative.add(address)
            if data.get('dadfailed'):
                failed.add(address)
            if data.get('secondary'):
                secondary.add(address)
        for family in (4, 6):
            data = json.loads(self._run([self.ip, '-j', '-N', f'-{family}', 'route', 'show',
                                        'table', 'main', 'dev', interface], **options))
            for route in data:
                destination = route.get('dst', 'default')
                if destination != 'default':
                    destination = str(ip_network(destination))
                routes.add(Route(family, destination, route.get('gateway'),
                                 int(route.get('protocol', 0)), int(route.get('metric', 0)),
                                 route.get('prefsrc')))
        return Snapshot(int(rows[0]['ifindex']), frozenset(addresses), frozenset(routes),
                        frozenset(tentative), frozenset(failed), frozenset(secondary))

    def set_alias(self, interface, rawbytes, **options):
        _interface(interface)
        if type(rawbytes) is not bytes or len(rawbytes) > 255 or b'\0' in rawbytes:
            raise ValueError('invalid network link alias bytes')
        # fsdecode/fsencode preserve arbitrary non-NUL alias bytes through the
        # subprocess argv with surrogateescape; no shell or text normalization.
        self._run([self.ip, 'link', 'set', 'dev', interface, 'alias', os.fsdecode(rawbytes)],
                  operation='native-alias', **options)

    def _address(self, action, interface, value, lease_seconds=None, **options):
        argv = [self.ip, f'-{value.family}', 'address', action, value.cidr, 'dev', interface,
                'proto', str(value.protocol)]
        if action != 'delete':
            argv.append('noprefixroute')
            if value.family == 4:
                if ip_interface(value.cidr).network.prefixlen < 31:
                    argv += ['broadcast', '+']
                argv += ['valid_lft', str(lease_seconds), 'preferred_lft', str(lease_seconds)]
        self._run(argv, **options)

    def add_address(self, interface, value, lease_seconds, **options):
        self._address('add', interface, value, lease_seconds, **options)

    def renew_address(self, interface, value, lease_seconds, **options):
        self._address('change', interface, value, lease_seconds, **options)

    def delete_address(self, interface, value, **options):
        self._address('delete', interface, value, **options)

    def _route(self, action, interface, value, **options):
        argv = [self.ip, f'-{value.family}', 'route', action, value.destination, 'table', 'main',
                'dev', interface, 'proto', str(value.protocol), 'metric', str(value.metric)]
        if value.gateway:
            argv += ['via', value.gateway]
        if value.source:
            argv += ['src', value.source]
        self._run(argv, **options)

    def add_route(self, interface, value, **options):
        self._route('add', interface, value, **options)

    def delete_route(self, interface, value, **options):
        self._route('delete', interface, value, **options)
