config:
  cloud-init.user-data: |
    #cloud-config
    hostname: dev
    manage_etc_hosts: true

    users:
      - default
      - name: jack
        lock_passwd: true
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /usr/bin/zsh

    package_update: true
    package_upgrade: true
    packages:
      - avahi-daemon
      - build-essential
      - curl
      - git
      - libnss-mdns
      - ssh-import-id
      - tmux
      - zsh

    no_ssh_fingerprints: true
    ssh:
      emit_keys_to_console: false

    runcmd:
      - [su, -, jack, -c, 'NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"']
      - [su, -, jack, -c, 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && curl -fsSL https://raw.githubusercontent.com/Spaceghost/.files/base/Brewfile | brew bundle --file=/dev/stdin']
      - [su, -, jack, -c, 'ssh-import-id gh:Spaceghost']
      - [systemctl, enable, --now, avahi-daemon]
