add_newline = false
format = "$username$hostname$directory${custom.fossil}$git_branch$git_status$cmd_duration$line_break$character"

[username]
show_always = true
style_user = "bold #C56A4A"
style_root = "bold #d57b71"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "#85c6ae"
format = "[@$hostname]($style) "

[directory]
style = "bold #D8C9A2"
truncation_length = 4
truncate_to_repo = false
read_only = " 󰌾"

[git_branch]
symbol = "󰘬 "
style = "#bb77c1"

[git_status]
style = "#d59871"

[cmd_duration]
min_time = 500
format = " [󱎫 $duration]($style)"
style = "#85a5c1"

[character]
success_symbol = "[❯](bold #99c671)"
error_symbol = "[❯](bold #d57b71)"

[custom.fossil]
command = "fossil branch current"
when = "fossil info >/dev/null 2>&1"
format = " [󰜘 $output]($style)"
style = "bold #C56A4A"
shell = ["sh"]
