xwayland disable
output HEADLESS-1 mode 1440x900
output HEADLESS-1 position 0 0
output * bg #13091f solid_color
seat seat0 fallback true
focus_follows_mouse no
mode "window-switcher" {
    bindsym Escape mode "default"
}
floating_modifier Mod4
default_border pixel 0
default_floating_border pixel 0
corner_radius 7
smart_corner_radius enable
layer_effects "oldbook-decoration" {
    corner_radius 0
}
for_window [app_id="attachment-floating"] floating enable, resize set 620 360, move absolute position 200 160
for_window [app_id="attachment-hover"] floating enable, resize set 420 280, move absolute position 900 120
