xwayland disable
output HEADLESS-1 mode 1280x800
output * bg #292336 solid_color
seat seat0 fallback true
focus_follows_mouse yes
mouse_warping none
default_border normal 2
default_floating_border normal 2
font monospace 12
corner_radius 0
shadows disable
blur disable
animation_duration_ms 0
for_window [app_id="^hover-"] floating enable
