xwayland disable
output HEADLESS-1 mode 1440x900
output * bg "/home/jack/.files/alpine/assets/gallery/themes/gruvbox-dark/2026-09-07-gruvbox-dark-alpine-rescue-0986082ea557.png" fill
seat seat0 fallback true
