xwayland disable
output HEADLESS-1 mode 1440x900
output * bg "/home/jack/.files/alpine/assets/gallery/themes/gruvbox-dark/2026-09-07-gruvbox-dark-yosemite-f932fef36c22.png" fill
seat seat0 fallback true
focus_follows_mouse no
include "/home/jack/.files/alpine/desktop/.config/swayfx/effects.conf"
include "/home/jack/.files/alpine/desktop/.config/sway/local.d/screenshot.conf"
