xwayland disable
output HEADLESS-1 mode 1440x900
output * bg #191324 solid_color
seat seat0 fallback true
focus_follows_mouse yes
mouse_warping none
gaps top 40
default_border pixel 0
default_floating_border pixel 0
for_window [app_id="^center-"] floating enable
set $mod Mod4
include /home/jack/.files/alpine/desktop/.config/sway/local.d/center.conf
