-- Self-contained Space Ghost: no plugin bootstrap or network dependency.
vim.cmd("highlight clear")
vim.o.background = "dark"
vim.g.colors_name = "gruvbox-dark"
local p = {
    bg = "#13091f", hard = "#0c0514", soft = "#1f152b", bg1 = "#261631",
    bg2 = "#49315b", bg3 = "#542476", fg = "#f3e9fa", bright = "#f5edfb",
    muted = "#816b91", red = "#ff6f91", green = "#8fe3b0", yellow = "#dca7ff",
    blue = "#8ab6ff", purple = "#c48bf0", aqua = "#9fe8ff", orange = "#ffb37a",
}
local groups = {
    Normal = { fg = p.fg, bg = p.bg },
    NormalNC = { fg = p.fg, bg = p.bg },
    NormalFloat = { fg = p.fg, bg = p.hard },
    FloatBorder = { fg = p.yellow, bg = p.hard },
    FloatTitle = { fg = p.yellow, bg = p.hard, bold = true },
    EndOfBuffer = { fg = p.bg2 },
    NonText = { fg = p.bg2 },
    Whitespace = { fg = p.bg2 },
    SpecialKey = { fg = p.bg2 },
    ColorColumn = { bg = p.soft },
    Cursor = { fg = p.hard, bg = p.yellow },
    CursorLine = { bg = p.soft },
    CursorColumn = { bg = p.soft },
    CursorLineNr = { fg = p.yellow, bold = true },
    LineNr = { fg = p.muted },
    SignColumn = { fg = p.muted, bg = p.bg },
    FoldColumn = { fg = p.aqua, bg = p.bg },
    Folded = { fg = p.muted, bg = p.bg1 },
    WinSeparator = { fg = p.bg2, bg = p.bg },
    Visual = { bg = p.bg2 },
    Search = { fg = p.hard, bg = p.yellow },
    IncSearch = { fg = p.hard, bg = p.orange },
    CurSearch = { fg = p.hard, bg = p.orange, bold = true },
    MatchParen = { fg = p.orange, bg = p.bg2, bold = true },
    StatusLine = { fg = p.fg, bg = p.bg2 },
    StatusLineNC = { fg = p.muted, bg = p.bg1 },
    TabLine = { fg = p.muted, bg = p.bg1 },
    TabLineFill = { bg = p.hard },
    TabLineSel = { fg = p.yellow, bg = p.bg, bold = true },
    Pmenu = { fg = p.fg, bg = p.bg1 },
    PmenuSel = { fg = p.hard, bg = p.yellow, bold = true },
    PmenuSbar = { bg = p.bg2 },
    PmenuThumb = { bg = p.muted },
    WildMenu = { fg = p.hard, bg = p.yellow },
    Directory = { fg = p.aqua },
    Title = { fg = p.yellow, bold = true },
    Question = { fg = p.green },
    MoreMsg = { fg = p.green },
    ModeMsg = { fg = p.yellow },
    WarningMsg = { fg = p.orange },
    ErrorMsg = { fg = p.red, bold = true },
    Comment = { fg = p.muted, italic = true },
    Constant = { fg = p.purple },
    String = { fg = p.green },
    Character = { fg = p.purple },
    Number = { fg = p.purple },
    Boolean = { fg = p.purple },
    Float = { fg = p.purple },
    Identifier = { fg = p.blue },
    Function = { fg = p.green, bold = true },
    Statement = { fg = p.red },
    Operator = { fg = p.orange },
    Keyword = { fg = p.red },
    PreProc = { fg = p.aqua },
    Type = { fg = p.yellow },
    Special = { fg = p.orange },
    Delimiter = { fg = p.fg },
    Underlined = { fg = p.blue, underline = true },
    Ignore = { fg = p.muted },
    Error = { fg = p.red, bold = true },
    Todo = { fg = p.hard, bg = p.yellow, bold = true },
    DiffAdd = { bg = "#1e232a" },
    DiffChange = { bg = "#19172c" },
    DiffDelete = { fg = p.red, bg = "#2d1426" },
    DiffText = { bg = "#384266" },
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.aqua },
    DiagnosticOk = { fg = p.green },
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.blue, undercurl = true },
    SpellLocal = { sp = p.aqua, undercurl = true },
    SpellRare = { sp = p.purple, undercurl = true },
}
for name, definition in pairs(groups) do
    vim.api.nvim_set_hl(0, name, definition)
end
for _, kind in ipairs({ "Error", "Warn", "Info", "Hint", "Ok" }) do
    vim.api.nvim_set_hl(0, "DiagnosticUnderline" .. kind,
        { sp = groups["Diagnostic" .. kind].fg, undercurl = true })
end
local ansi = { p.bg, "#b34e6d", "#679d82", "#9c74b7", "#647fb7", "#8b61ad",
    "#72a1b7", "#b9a3cc", p.muted, p.red, p.green, p.yellow, p.blue, p.purple,
    p.aqua, p.bright }
for index, color in ipairs(ansi) do
    vim.g["terminal_color_" .. (index - 1)] = color
end
