xwayland disable
output HEADLESS-1 mode 1280x800
output * bg #0c1016 solid_color
seat seat0 fallback true
include "/tmp/oldbook-theme-switch-7ozr_w9m/home/.config/sway/theme.conf"
include "/tmp/oldbook-theme-switch-7ozr_w9m/home/.config/swayfx/effects.conf"
for_window [app_id="theme-switch-preview"] floating enable
for_window [app_id="theme-switch-preview"] resize set 870 470
for_window [app_id="theme-switch-preview"] move position center
