-- Spaceghost colorscheme: void black, spectral violet, ion mint, signal amber.
local p = require('spaceghost.palette')
vim.cmd.highlight('clear')
vim.g.colors_name = 'spaceghost'
vim.o.background = 'dark'
vim.o.termguicolors = true

for i, c in ipairs(p.terminal) do vim.g['terminal_color_' .. (i - 1)] = c end

local function hi(group, spec) vim.api.nvim_set_hl(0, group, spec) end
local groups = {
  Normal = { fg = p.fg, bg = p.bg0 },
  NormalNC = { fg = p.fg, bg = p.bg0 },
  NormalFloat = { fg = p.fg, bg = p.bg0 },
  FloatBorder = { fg = p.violet, bg = p.bg0 },
  FloatTitle = { fg = p.bg0, bg = p.violet, bold = true },
  WinSeparator = { fg = p.border, bg = p.bg0 },
  EndOfBuffer = { fg = p.bg0 },
  SignColumn = { bg = p.bg0 },
  LineNr = { fg = p.dim },
  LineNrAbove = { fg = p.dim },
  LineNrBelow = { fg = p.dim },
  CursorLineNr = { fg = p.mint, bold = true },
  CursorLine = { bg = p.bg1 },
  CursorColumn = { bg = p.bg1 },
  ColorColumn = { bg = p.bg1 },
  Cursor = { fg = p.bg0, bg = p.mint },
  TermCursor = { fg = p.bg0, bg = p.mint },
  TermCursorNC = { fg = p.bg0, bg = p.muted },
  Visual = { fg = p.bg0, bg = p.violet },
  VisualNOS = { fg = p.bg0, bg = p.violet },
  Search = { fg = p.bg0, bg = p.amber },
  IncSearch = { fg = p.bg0, bg = p.mint },
  CurSearch = { fg = p.bg0, bg = p.mint },
  Substitute = { fg = p.bg0, bg = p.amber },
  MatchParen = { fg = p.amber, bold = true, underline = true },
  Folded = { fg = p.muted, bg = p.bg1 },
  FoldColumn = { fg = p.dim },
  NonText = { fg = p.dim },
  Whitespace = { fg = p.border },
  SpecialKey = { fg = p.dim },
  Conceal = { fg = p.muted },
  Directory = { fg = p.violet },
  Title = { fg = p.violet, bold = true },
  Question = { fg = p.mint },
  MoreMsg = { fg = p.mint },
  ModeMsg = { fg = p.muted },
  MsgArea = { fg = p.fg },
  ErrorMsg = { fg = p.alert, bold = true },
  WarningMsg = { fg = p.amber },
  StatusLine = { fg = p.muted, bg = p.bg1 },
  StatusLineNC = { fg = p.dim, bg = p.bg1 },
  TabLine = { fg = p.muted, bg = p.bg0 },
  TabLineFill = { bg = p.bg0 },
  TabLineSel = { fg = p.bg0, bg = p.mint, bold = true },
  WinBar = { fg = p.muted, bg = p.bg0 },
  WinBarNC = { fg = p.dim, bg = p.bg0 },
  Pmenu = { fg = p.fg, bg = p.bg1 },
  PmenuSel = { fg = p.bg0, bg = p.violet, bold = true },
  PmenuSbar = { bg = p.bg2 },
  PmenuThumb = { bg = p.violet },
  WildMenu = { fg = p.bg0, bg = p.violet },
  QuickFixLine = { bg = p.bg2 },
  SpellBad = { sp = p.alert, undercurl = true },
  SpellCap = { sp = p.amber, undercurl = true },
  SpellRare = { sp = p.violet, undercurl = true },
  SpellLocal = { sp = p.cyan, undercurl = true },

  Comment = { fg = p.muted, italic = true },
  Constant = { fg = p.orange },
  String = { fg = p.mint },
  Character = { fg = p.mint },
  Number = { fg = p.orange },
  Boolean = { fg = p.orange },
  Float = { fg = p.orange },
  Identifier = { fg = p.fg },
  Function = { fg = p.blue },
  Statement = { fg = p.violet },
  Conditional = { fg = p.violet },
  Repeat = { fg = p.violet },
  Label = { fg = p.violet },
  Operator = { fg = p.cyan },
  Keyword = { fg = p.violet, italic = true },
  Exception = { fg = p.alert },
  PreProc = { fg = p.amber },
  Include = { fg = p.amber },
  Define = { fg = p.amber },
  Macro = { fg = p.amber },
  Type = { fg = p.amber },
  StorageClass = { fg = p.amber },
  Structure = { fg = p.amber },
  Typedef = { fg = p.amber },
  Special = { fg = p.cyan },
  SpecialChar = { fg = p.cyan },
  Tag = { fg = p.blue },
  Delimiter = { fg = p.muted },
  SpecialComment = { fg = p.muted, bold = true },
  Debug = { fg = p.alert },
  Underlined = { underline = true },
  Ignore = { fg = p.dim },
  Error = { fg = p.alert, bold = true },
  Todo = { fg = p.bg0, bg = p.amber, bold = true },
  Added = { fg = p.mint },
  Changed = { fg = p.amber },
  Removed = { fg = p.alert },

  DiffAdd = { bg = '#15302a' },
  DiffChange = { bg = '#2b2a1b' },
  DiffDelete = { fg = p.alert, bg = '#331a26' },
  DiffText = { fg = p.bg0, bg = p.amber },
  diffAdded = { fg = p.mint },
  diffRemoved = { fg = p.alert },
  diffChanged = { fg = p.amber },
  diffFile = { fg = p.violet },
  diffLine = { fg = p.cyan },

  DiagnosticError = { fg = p.alert },
  DiagnosticWarn = { fg = p.amber },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.cyan },
  DiagnosticOk = { fg = p.mint },
  DiagnosticUnderlineError = { sp = p.alert, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.amber, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.cyan, undercurl = true },

  gitcommitSummary = { fg = p.fg, bold = true },
  gitcommitOverflow = { fg = p.alert },
  gitcommitComment = { fg = p.muted, italic = true },
  gitcommitSelectedFile = { fg = p.mint },
  gitcommitDiscardedFile = { fg = p.alert },
  gitcommitUntrackedFile = { fg = p.amber },
  gitcommitBranch = { fg = p.violet, bold = true },

  ['@variable'] = { fg = p.fg },
  ['@variable.builtin'] = { fg = p.alert },
  ['@variable.parameter'] = { fg = p.fg, italic = true },
  ['@property'] = { fg = p.blue },
  ['@field'] = { fg = p.blue },
  ['@constant'] = { fg = p.orange },
  ['@constant.builtin'] = { fg = p.orange },
  ['@string'] = { fg = p.mint },
  ['@string.escape'] = { fg = p.cyan },
  ['@function'] = { fg = p.blue },
  ['@function.builtin'] = { fg = p.blue },
  ['@function.macro'] = { fg = p.amber },
  ['@method'] = { fg = p.blue },
  ['@constructor'] = { fg = p.amber },
  ['@keyword'] = { fg = p.violet, italic = true },
  ['@keyword.return'] = { fg = p.violet, italic = true },
  ['@operator'] = { fg = p.cyan },
  ['@punctuation.bracket'] = { fg = p.muted },
  ['@punctuation.delimiter'] = { fg = p.muted },
  ['@type'] = { fg = p.amber },
  ['@type.builtin'] = { fg = p.amber },
  ['@tag'] = { fg = p.blue },
  ['@tag.attribute'] = { fg = p.amber },
  ['@tag.delimiter'] = { fg = p.muted },
  ['@comment'] = { fg = p.muted, italic = true },
  ['@markup.heading'] = { fg = p.violet, bold = true },
  ['@markup.link'] = { fg = p.cyan, underline = true },
  ['@markup.raw'] = { fg = p.mint },
  ['@markup.list'] = { fg = p.violet },

  -- Spaceghost chrome
  SpaceghostBadge = { fg = p.bg0, bg = p.violet, bold = true },
  SpaceghostSurface = { fg = p.fg, bg = p.bg1 },
  SpaceghostMuted = { fg = p.muted, bg = p.bg0 },
  SpaceghostTab = { fg = p.muted, bg = p.bg0 },
  SpaceghostTabNew = { fg = p.fg, bg = p.bg3 },
  SpaceghostTabSel = { fg = p.bg0, bg = p.mint, bold = true },
  SpaceghostStateLive = { fg = p.muted, bg = p.bg0 },
  SpaceghostStateNew = { fg = p.amber, bg = p.bg3, bold = true },
  SpaceghostStateExit = { fg = p.alert, bg = p.bg0 },
  SpaceghostModeNormal = { fg = p.bg0, bg = p.violet, bold = true },
  SpaceghostModeInsert = { fg = p.bg0, bg = p.mint, bold = true },
  SpaceghostModeVisual = { fg = p.bg0, bg = p.amber, bold = true },
  SpaceghostModeTerminal = { fg = p.bg0, bg = p.mint, bold = true },
  SpaceghostModeReplace = { fg = p.bg0, bg = p.alert, bold = true },
  SpaceghostModeCommand = { fg = p.bg0, bg = p.amber, bold = true },
  SpaceghostStatusCwd = { fg = p.fg, bg = p.bg1 },
  SpaceghostStatusAccent = { fg = p.mint, bg = p.bg1 },
  SpaceghostStatusBranch = { fg = p.violet, bg = p.bg1 },
  SpaceghostStatusWarn = { fg = p.amber, bg = p.bg1 },
  SpaceghostStatusAlert = { fg = p.alert, bg = p.bg1 },
  SpaceghostMenuKey = { fg = p.mint, bold = true },
  SpaceghostMenuHint = { fg = p.muted, italic = true },
  SpaceghostMenuSel = { fg = p.bg0, bg = p.violet, bold = true },
}
for group, spec in pairs(groups) do hi(group, spec) end
