[Icon Theme]
Name=MBP Intel Gruvbox
Comment=Warm Gruvbox folders with Papirus Dark application icons
Inherits=Papirus-Dark,hicolor
Example=folder
Directories=128x128/places,16x16/places,22x22/places,24x24/places,32x32/places,48x48/places,64x64/places,96x96/places

[128x128/places]
Context=Places
Size=128
Type=Fixed

[16x16/places]
Context=Places
Size=16
Type=Fixed

[22x22/places]
Context=Places
Size=22
Type=Fixed

[24x24/places]
Context=Places
Size=24
Type=Fixed

[32x32/places]
Context=Places
Size=32
Type=Fixed

[48x48/places]
Context=Places
Size=48
Type=Fixed

[64x64/places]
Context=Places
Size=64
Type=Fixed

[96x96/places]
Context=Places
Size=96
Type=Fixed
