xwayland disable
output HEADLESS-1 mode 1440x900
output HEADLESS-1 bg #130a20 solid_color
seat seat0 fallback true
for_window [app_id="^(io[.]github[.]Pithos|pithos)$"] move scratchpad
for_window [class="^Pithos$"] move scratchpad
