-- Self-contained Catppuccin Mocha: no plugin bootstrap or network dependency.
vim.cmd("highlight clear")
vim.o.background = "dark"
vim.g.colors_name = "catppuccin-mocha"
local p = {
    bg = "#1e1e2e", hard = "#11111b", soft = "#282839", bg1 = "#313244",
    bg2 = "#45475a", bg3 = "#585b70", fg = "#cdd6f4", bright = "#d7def6",
    muted = "#6c7086", red = "#f38ba8", green = "#a6e3a1", yellow = "#f9e2af",
    blue = "#89b4fa", purple = "#cba6f7", aqua = "#94e2d5", orange = "#fab387",
}
local groups = {
    Normal = { fg = p.fg, bg = p.bg },
    NormalNC = { fg = p.fg, bg = p.bg },
    NormalFloat = { fg = p.fg, bg = p.hard },
    FloatBorder = { fg = p.yellow, bg = p.hard },
    FloatTitle = { fg = p.yellow, bg = p.hard, bold = true },
    EndOfBuffer = { fg = p.bg2 },
    NonText = { fg = p.bg2 },
    Whitespace = { fg = p.bg2 },
    SpecialKey = { fg = p.bg2 },
    ColorColumn = { bg = p.soft },
    Cursor = { fg = p.hard, bg = p.yellow },
    CursorLine = { bg = p.soft },
    CursorColumn = { bg = p.soft },
    CursorLineNr = { fg = p.yellow, bold = true },
    LineNr = { fg = p.muted },
    SignColumn = { fg = p.muted, bg = p.bg },
    FoldColumn = { fg = p.aqua, bg = p.bg },
    Folded = { fg = p.muted, bg = p.bg1 },
    WinSeparator = { fg = p.bg2, bg = p.bg },
    Visual = { bg = p.bg2 },
    Search = { fg = p.hard, bg = p.yellow },
    IncSearch = { fg = p.hard, bg = p.orange },
    CurSearch = { fg = p.hard, bg = p.orange, bold = true },
    MatchParen = { fg = p.orange, bg = p.bg2, bold = true },
    StatusLine = { fg = p.fg, bg = p.bg2 },
    StatusLineNC = { fg = p.muted, bg = p.bg1 },
    TabLine = { fg = p.muted, bg = p.bg1 },
    TabLineFill = { bg = p.hard },
    TabLineSel = { fg = p.yellow, bg = p.bg, bold = true },
    Pmenu = { fg = p.fg, bg = p.bg1 },
    PmenuSel = { fg = p.hard, bg = p.yellow, bold = true },
    PmenuSbar = { bg = p.bg2 },
    PmenuThumb = { bg = p.muted },
    WildMenu = { fg = p.hard, bg = p.yellow },
    Directory = { fg = p.aqua },
    Title = { fg = p.yellow, bold = true },
    Question = { fg = p.green },
    MoreMsg = { fg = p.green },
    ModeMsg = { fg = p.yellow },
    WarningMsg = { fg = p.orange },
    ErrorMsg = { fg = p.red, bold = true },
    Comment = { fg = p.muted, italic = true },
    Constant = { fg = p.purple },
    String = { fg = p.green },
    Character = { fg = p.purple },
    Number = { fg = p.purple },
    Boolean = { fg = p.purple },
    Float = { fg = p.purple },
    Identifier = { fg = p.blue },
    Function = { fg = p.green, bold = true },
    Statement = { fg = p.red },
    Operator = { fg = p.orange },
    Keyword = { fg = p.red },
    PreProc = { fg = p.aqua },
    Type = { fg = p.yellow },
    Special = { fg = p.orange },
    Delimiter = { fg = p.fg },
    Underlined = { fg = p.blue, underline = true },
    Ignore = { fg = p.muted },
    Error = { fg = p.red, bold = true },
    Todo = { fg = p.hard, bg = p.yellow, bold = true },
    DiffAdd = { bg = "#262e2e" },
    DiffChange = { bg = "#1e2233" },
    DiffDelete = { fg = p.red, bg = "#31222f" },
    DiffText = { bg = "#3c4a6a" },
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.aqua },
    DiagnosticOk = { fg = p.green },
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.blue, undercurl = true },
    SpellLocal = { sp = p.aqua, undercurl = true },
    SpellRare = { sp = p.purple, undercurl = true },
}
for name, definition in pairs(groups) do
    vim.api.nvim_set_hl(0, name, definition)
end
for _, kind in ipairs({ "Error", "Warn", "Info", "Hint", "Ok" }) do
    vim.api.nvim_set_hl(0, "DiagnosticUnderline" .. kind,
        { sp = groups["Diagnostic" .. kind].fg, undercurl = true })
end
local ansi = { p.bg, "#af6881", "#7aa47c", "#b3a386", "#6784b9", "#947ab7",
    "#6ea3a0", "#a6adc8", p.muted, p.red, p.green, p.yellow, p.blue, p.purple,
    p.aqua, p.bright }
for index, color in ipairs(ansi) do
    vim.g["terminal_color_" .. (index - 1)] = color
end
