xwayland disable
output HEADLESS-1 mode 1440x900
output * bg #1d2021 solid_color
seat seat0 fallback true
focus_follows_mouse no
mouse_warping none
include /home/jack/.files/alpine/desktop/.config/sway/theme.conf
bindsym --release button2 floating toggle
default_border normal 2
default_floating_border normal 2
gaps inner 0
gaps outer 0
corner_radius 0
shadows disable
blur disable
animation_duration_ms 0

include /home/jack/.files/alpine/desktop/.config/swayfx/effects.conf
titlebar_position bottom
default_border normal 0
default_floating_border normal 0
